# Generated by Django 4.0 on 2022-04-14 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='Patient_doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='patient_doctor', to='management.doctor'),
        ),
        migrations.AddField(
            model_name='patient',
            name='Patient_id',
            field=models.CharField(blank=True, default='Please Update', max_length=200, null=True, unique=True),
        ),
    ]
