# Generated by Django 4.0 on 2022-04-14 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_patient_patient_doctor_patient_patient_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='Patient_blood_genotype',
            field=models.CharField(default='Please Update', max_length=200),
        ),
        migrations.AddField(
            model_name='patient',
            name='Patient_blood_group',
            field=models.CharField(default='Please Update', max_length=200),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Patient_doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_doctor', to='management.doctor'),
        ),
    ]
