# Generated by Django 4.0 on 2022-04-14 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_patient_patient_blood_genotype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='Patient_email_address',
            field=models.EmailField(blank=True, default='Null_provided@email.com', max_length=250, null=True),
        ),
    ]
