# Generated by Django 4.0 on 2022-04-15 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_patient_patient_email_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alloted_Beds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Alloted_time', models.DateTimeField(auto_now_add=True)),
                ('Discharge_time', models.DateTimeField(blank=True)),
                ('Alloted_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.patient')),
                ('Bed_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.room')),
            ],
        ),
    ]
