# Generated by Django 4.0 on 2022-04-15 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_alloted_beds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alloted_beds',
            name='Alloted_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
