# Generated by Django 4.0 on 2022-04-15 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_alter_alloted_beds_alloted_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alloted_beds',
            name='Discharge_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
