# Generated by Django 4.0.3 on 2022-04-16 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_alter_alloted_beds_discharge_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nurse_lastname', models.CharField(max_length=250)),
                ('Nurse_firstname', models.CharField(max_length=250)),
                ('Nurse_email_address', models.EmailField(blank=True, default='email@hospitalmanagent.com', max_length=250, null=True)),
                ('Nurse_phone_number', models.CharField(max_length=250)),
                ('Nurse_location', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Other_Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Other_lastname', models.CharField(max_length=250)),
                ('Other_firstname', models.CharField(max_length=250)),
                ('Other_email', models.EmailField(blank=True, default='otherstaff@hospitalmanagement.com', max_length=250, null=True)),
                ('Other_phone', models.CharField(max_length=250)),
                ('Other_address', models.CharField(max_length=250)),
                ('Other_role', models.CharField(blank=True, choices=[('UNDECIDED', 'UNDECIDED'), ('CLEANER', 'CLEANER'), ('CLERK', 'CLERK'), ('COOK', 'COOK'), ('MATRON', 'MATRON'), ('MIDWIFE', 'MIDWIFE'), ('DOCTOR IN TRAINING', 'DOCTOR IN TRAINING'), ('LAB TECHNICIAN', 'LAB TECHNICIAN'), ('LAB ASSISTANT', 'LAB ASSISTANT')], default='UNDECIDED', max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='alloted_beds',
            name='Discharge_time',
        ),
        migrations.AddField(
            model_name='appointment',
            name='Assigned_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.doctor'),
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('quantity_available', models.IntegerField()),
                ('nafdac_no', models.CharField(max_length=200)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField()),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.other_staff')),
            ],
        ),
    ]
