# Generated by Django 4.0.3 on 2022-04-16 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_nurse_other_staff_remove_alloted_beds_discharge_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('blood_group', models.CharField(max_length=250)),
                ('bloood_genotype', models.CharField(max_length=250)),
                ('date_donated', models.DateTimeField(auto_now_add=True, null=True)),
                ('amount_donated', models.CharField(blank=True, max_length=250, null=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.patient')),
            ],
        ),
    ]
