# Generated by Django 4.0.3 on 2022-04-17 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_operation_birth_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='donors',
            name='donor_contact',
            field=models.CharField(default='Please Update', max_length=250),
        ),
    ]
