# Generated by Django 4.0.3 on 2022-04-20 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0012_donors_donor_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='Doctor_user_instance',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
