# Generated by Django 4.0.3 on 2022-04-22 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_alter_doctor_doctor_user_instance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alloted_beds',
            name='Alloted_time',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
