# Generated by Django 4.0.3 on 2022-04-22 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_alter_alloted_beds_alloted_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alloted_beds',
            name='Alloted_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
