# Generated by Django 4.0.3 on 2022-04-22 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_alter_alloted_beds_alloted_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='Doctor_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_department', to='management.department'),
        ),
    ]
