# Generated by Django 4.0.3 on 2022-04-22 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0017_alter_doctor_doctor_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='Doctor_user_instance',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
