# Generated by Django 4.0.3 on 2022-04-23 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0019_doctor_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='Profile_image',
            field=models.ImageField(blank=True, default='Null', null=True, upload_to=''),
        ),
    ]
