# Generated by Django 4.0.3 on 2022-08-08 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0022_nurse_nurse_user_instance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={},
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='Appointment_date',
        ),
    ]
