# Generated by Django 4.0.3 on 2022-08-09 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0025_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='body_of_blog',
            field=models.TextField(max_length=200000),
        ),
    ]
