# Generated by Django 4.0.3 on 2022-04-08 11:22

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department_name', models.CharField(blank=True, max_length=250, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Room_location', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient_lastname', models.CharField(blank=True, max_length=250, null=True)),
                ('Patient_firstname', models.CharField(blank=True, max_length=250, null=True)),
                ('Patient_phone_number', models.CharField(blank=True, max_length=120, null=True)),
                ('Patient_address', models.CharField(blank=True, max_length=350, null=True)),
                ('Patient_age', models.IntegerField(blank=True, max_length=1000, null=True)),
                ('Patient_gender', models.CharField(choices=[('UNDECIDED', 'UNDECIDED'), ('MALE', 'MALE'), ('FEMALE', 'FEMALE')], default='UNDECIDED', max_length=25)),
                ('Patient_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.fields.CharField, to='base.rooms')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Doctor_firstname', models.CharField(blank=True, max_length=250, null=True)),
                ('Doctor_lastname', models.CharField(blank=True, max_length=250, null=True)),
                ('Doctor_gender', models.CharField(choices=[('UNDECIDED', 'UNDECIDED'), ('MALE', 'MALE'), ('FEMALE', 'FEMALE')], default='UNDECIDED', max_length=25)),
                ('Doctor_specialization', models.CharField(blank=True, max_length=250, null=True)),
                ('Doctor_phone_number', models.CharField(blank=True, max_length=250, null=True)),
                ('Doctor_email_address', models.EmailField(blank=True, default='firstname.lastname@hospitalmanagement.com', max_length=254, null=True)),
                ('Doctor_location', models.CharField(blank=True, max_length=250, null=True)),
                ('Doctor_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_department', to='base.departments')),
            ],
        ),
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.FloatField(max_length=2000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('patient_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.patient')),
            ],
        ),
    ]
