# Generated by Django 4.0.3 on 2022-04-08 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='Patient_age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
