# Generated by Django 4.0.3 on 2022-04-08 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_patient_patient_age'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bills',
            new_name='Bill',
        ),
        migrations.RenameModel(
            old_name='Departments',
            new_name='Department',
        ),
        migrations.RenameModel(
            old_name='Rooms',
            new_name='Room',
        ),
    ]
