# Generated by Django 4.0.3 on 2022-04-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_bills_bill_rename_departments_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='Room_availability',
            field=models.BooleanField(default=False),
        ),
    ]
