# Generated by Django 4.0.3 on 2022-04-08 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_room_room_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='Room_ID',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
