# Generated by Django 4.0.3 on 2022-04-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_department_department_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(max_length=250)),
                ('Contact_email', models.EmailField(blank=True, default='Not Provided', max_length=500, null=True)),
                ('Contact_phone', models.CharField(max_length=250)),
                ('Appointment_date', models.DateTimeField()),
                ('Reason_for_Appointment', models.TextField(max_length=2500)),
                ('Appointment_completed', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'ordering': ['-Appointment_date'],
            },
        ),
    ]
