# Generated by Django 4.0.3 on 2022-04-10 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Contact_email',
            field=models.EmailField(blank=True, default='notprovided@example.com', max_length=500, null=True),
        ),
    ]
