# Generated by Django 4.0 on 2022-04-14 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_appointment_contact_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['Appointment_date']},
        ),
    ]
