# Generated by Django 4.0.3 on 2022-04-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_appointment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Appointment_date',
            field=models.DateField(),
        ),
    ]
